image: ghcr.io/cirruslabs/flutter
stages:
  - lints
  - tests
  - build

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

lints:
  stage: lints
  before_script:
    - bash reconfigure.sh
  script:
    - flutter analyze
  tags:
    - flutter

unit tests:
  stage: tests
  script:
    - flutter test --coverage ./lib
    - lcov -r coverage/lcov.info '*/__test*__/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  tags:
    - flutter
  artifacts:
    paths:
      - coverage

ios:
  stage: build
  before_script:
    - gem install bundler
    - bundle install
    - flutter pub get
  script:
    - flutter build ios --release --no-codesign
    - cd ios && bundle exec fastlane gym --scheme "Runner" --clean --output_directory "../build/ios" --output_name "Runner.ipa"
  artifacts:
    paths:
      - build/ios/*.ipa
  tags:
    - flutter