image: ghcr.io/cirruslabs/flutter:stable  # Image có sẵn Flutter & Dart

stages:
  - patch

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "feature/handle-to-use-shorebird"'

variables:
  SHOREBIRD_TOKEN: $SHOREBIRD_TOKEN
  SHOREBIRD_VERSION: stable

patch_android:
  stage: patch
  before_script:
    - apt-get update && apt-get install -y curl unzip git
    - echo "📦 Installing Shorebird CLI..."
    - curl -s https://raw.githubusercontent.com/shorebirdtech/shorebird/main/install.sh | bash
    - export PATH="$HOME/.shorebird/bin:$PATH"
    - shorebird --version
    - echo "🔑 Authenticating Shorebird..."
    - echo "$SHOREBIRD_TOKEN" | shorebird login --no-prompt
  script:
    - echo "🚀 Creating patch for Android..."
    - shorebird release android
    - shorebird patch android
