name: shopping

description:
  Shopping is an e-commerce application for purchasing furniture, lighting, cabinets, and other home essentials online.
  Users can browse a variety of products, place orders, and manage their purchases conveniently.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  auto_route: 8.1.3
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.1

  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  showcaseview: ^3.0.0
  hooks_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  shimmer: ^3.0.0
  riverpod_annotation: ^2.3.5
  path_provider: ^2.1.3
  webview_flutter: ^4.8.0
  gap: ^3.0.1
  intl: ^0.18.1
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.4
  freezed: ^2.5.7
  cached_query: ^2.2.1
  mocktail: ^1.0.4

dependency_overrides:
  intl: 0.18.1

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_asset_generator: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.5.4
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.0

flutter:
  # generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Gelasio
      fonts:
        - asset: assets/fonts/Gelasio/Gelasio-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
    - family: Nunito_Sans
      fonts:
        - asset: assets/fonts/Nunito_Sans/NunitoSans-Regular.ttf
